### ISSUE TITLE
ADD - Script Template

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/Automation#6]
We currently generate the newsletter and archive from the issues template. 

I would like to add a shownotes template and script. for the brief. These don't necessarily need to be saved to a file. My suggestion is to print these or have them display in some way. This could be using something like [textual](https://textualize.io) to display the content and possible copy to clipboard.

## Shownotes
Include:
- summary of the show (**Add manual addition to the publish show document**)
- list of links for the topics (Title - Link)
- standardized text at the bottom

## Script for the brief
Include:
- Intro
- Topics with links removed
- standardized text at the bottom

**Comment by jonafato** [comment]
+1 here. I currently copy and past the text into a text document before recording the brief, but we don't publish that anywhere and probably should. One thing I think we'll need to figure out is how to account for ordering the topics, since we try to keep them grouped by category or shared context. Maybe this is an interactive CLI or something that shows you the topics to let you choose their order before outputting them to a script?

**Comment by kjaymiller** [comment]
Reposting this into Topics as the YouTube Copy is another add that I'd like to see
